# ch5. getting started with pandas

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## intro to pandas data structure

## Series

In [4]:
obj = pd.Series([4, 8, -5, 2])
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [5]:
# the value attribute
obj.values

array([ 4,  8, -5,  2])

In [6]:
# the index attribute
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([3, -2, 6, 88], index=['a', 'b', 'c', 'd'])
obj2

a     3
b    -2
c     6
d    88
dtype: int64

In [8]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj2.values

array([ 3, -2,  6, 88])

In [10]:
pd.__version__

'1.0.3'

In [11]:
# get one value by its index
obj2['b']

-2

In [12]:
# get multiple values by their index as a list
obj2[['b', 'd', 'a', 'c']]

b    -2
d    88
a     3
c     6
dtype: int64

In [13]:
# filter by boolean array
obj2[obj2 > 5]

c     6
d    88
dtype: int64

In [14]:
obj2 * 2

a      6
b     -4
c     12
d    176
dtype: int64

In [15]:
np.exp(obj2)

a    2.008554e+01
b    1.353353e-01
c    4.034288e+02
d    1.651636e+38
dtype: float64

In [16]:
# series as a dict
'c' in obj2

True

In [17]:
'k' in obj2

False

In [18]:
# create Series from dict
sdata = {'Ohio': 344, 'Texas': 873, 'Utah': 486}
obj3 = pd.Series(sdata)
obj3

Ohio     344
Texas    873
Utah     486
dtype: int64

In [19]:
# override index
states = ['Cal', 'Ohio', 'NY']
obj4 = pd.Series(sdata, index=states)
obj4

Cal       NaN
Ohio    344.0
NY        NaN
dtype: float64

In [20]:
pd.isnull(obj4)

Cal      True
Ohio    False
NY       True
dtype: bool

In [21]:
pd.isnull(obj4).sum()

2

In [22]:
pd.notnull(obj4).sum()

1

In [23]:
obj4.isnull()

Cal      True
Ohio    False
NY       True
dtype: bool

In [24]:
obj.isnull().sum()

0

In [25]:
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [26]:
obj4

Cal       NaN
Ohio    344.0
NY        NaN
dtype: float64

In [27]:
obj3 + obj4

Cal        NaN
NY         NaN
Ohio     688.0
Texas      NaN
Utah       NaN
dtype: float64

In [28]:
obj4.name = 'population'

In [29]:
obj4.index.name = 'state'

In [30]:
obj4

state
Cal       NaN
Ohio    344.0
NY        NaN
Name: population, dtype: float64

In [31]:
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [32]:
obj.index = ['b', 's', 'j', 'r']
obj

b    4
s    8
j   -5
r    2
dtype: int64

## DataFrame

In [33]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(
    data, 
    columns=['year', 'state', 'pop', 'debt'], 
    index=['one', 'two', 'three', 'four', 'five', 'six']
)
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [40]:
type(frame2['state'])

pandas.core.series.Series

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [42]:
frame2['state']['two':'four']

two        Ohio
three      Ohio
four     Nevada
Name: state, dtype: object

In [43]:
frame2['state'].name

'state'

In [44]:
frame2['state'].index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [45]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [46]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [47]:
frame2['debt'] = np.arange(6.0)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [48]:
val = pd.Series(
    [-1.2, -1.5, -1.7], 
    index=['two', 'four', 'seven']
    )
val

two     -1.2
four    -1.5
seven   -1.7
dtype: float64

In [49]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [50]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [51]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
pop = {
    'Nevada' : {2001: 2.4, 2002: 2.9}, 
    'Ohio'   : {2000: 1.5, 2001: 1.7, 2002: 3.6}
}

In [54]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [55]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [56]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [57]:
pdata = {
    'Ohio'   : frame3['Ohio'][:-1],
    'Nevada' : frame3['Nevada'][:2]
}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [58]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [59]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [60]:
three_d_arr = np.array([
    [[1, 2], [2, 1]], 
    [[3, 4], [4, 3]],
    [[5, 6], [6, 5]]
])
three_d_arr

array([[[1, 2],
        [2, 1]],

       [[3, 4],
        [4, 3]],

       [[5, 6],
        [6, 5]]])

In [61]:
three_d_arr[0]

array([[1, 2],
       [2, 1]])

In [62]:
frame3['3d_array'] = [three_d_arr[0], three_d_arr[1], three_d_arr[2]]
frame3

state  Nevada  Ohio          3d_array
year                                 
2001      2.4   1.7  [[1, 2], [2, 1]]
2002      2.9   3.6  [[3, 4], [4, 3]]
2000      NaN   1.5  [[5, 6], [6, 5]]

In [63]:
frame3.values

array([[2.4, 1.7, array([[1, 2],
       [2, 1]])],
       [2.9, 3.6, array([[3, 4],
       [4, 3]])],
       [nan, 1.5, array([[5, 6],
       [6, 5]])]], dtype=object)

In [64]:
frame3['3d_array']

year
2001    [[1, 2], [2, 1]]
2002    [[3, 4], [4, 3]]
2000    [[5, 6], [6, 5]]
Name: 3d_array, dtype: object

In [65]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## index objects

In [66]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [67]:
index[1:]

Index(['b', 'c'], dtype='object')

In [69]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [71]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [72]:
obj2.index is labels

True

In [73]:
frame3

state  Nevada  Ohio          3d_array
year                                 
2001      2.4   1.7  [[1, 2], [2, 1]]
2002      2.9   3.6  [[3, 4], [4, 3]]
2000      NaN   1.5  [[5, 6], [6, 5]]

In [74]:
frame3.columns

Index(['Nevada', 'Ohio', '3d_array'], dtype='object', name='state')

In [75]:
'Ohin' in frame3.columns

False

In [76]:
2003 in frame3.index

False

In [80]:
frame3.drop(['3d_array'], axis=1)

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [81]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 essential functionality

### reindexing

In [83]:
obj = pd.Series(
    [4.5, 7.2, -5.3, 3.6], 
    index=['d', 'b','a', 'c']
)
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [84]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [85]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [86]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [87]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [88]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [91]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### drop entires from an axis

In [92]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [93]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [94]:
obj.drop(['d', 'a'])

b    1.0
c    2.0
e    4.0
dtype: float64

In [95]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [96]:

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.drop(['Ohio', 'Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [103]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
obj.drop('c', inplace=True)

In [105]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [106]:
data.drop(['one', 'four'], axis=1, inplace=True)

In [107]:
data

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

### indexing, selection, filtering