# ch5. getting started with pandas

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## intro to pandas data structure

## Series

In [4]:
obj = pd.Series([4, 8, -5, 2])
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [5]:
# the value attribute
obj.values

array([ 4,  8, -5,  2])

In [6]:
# the index attribute
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([3, -2, 6, 88], index=['a', 'b', 'c', 'd'])
obj2

a     3
b    -2
c     6
d    88
dtype: int64

In [8]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj2.values

array([ 3, -2,  6, 88])

In [10]:
pd.__version__

'1.0.2'

In [11]:
# get one value by its index
obj2['b']

-2

In [12]:
# get multiple values by their index as a list
obj2[['b', 'd', 'a', 'c']]

b    -2
d    88
a     3
c     6
dtype: int64

In [13]:
# filter by boolean array
obj2[obj2 > 5]

c     6
d    88
dtype: int64

In [14]:
obj2 * 2

a      6
b     -4
c     12
d    176
dtype: int64

In [15]:
np.exp(obj2)

a    2.008554e+01
b    1.353353e-01
c    4.034288e+02
d    1.651636e+38
dtype: float64

In [16]:
# series as a dict
'c' in obj2

True

In [17]:
'k' in obj2

False

In [18]:
# create Series from dict
sdata = {'Ohio': 344, 'Texas': 873, 'Utah': 486}
obj3 = pd.Series(sdata)
obj3

Ohio     344
Texas    873
Utah     486
dtype: int64

In [19]:
# override index
states = ['Cal', 'Ohio', 'NY']
obj4 = pd.Series(sdata, index=states)
obj4

Cal       NaN
Ohio    344.0
NY        NaN
dtype: float64

In [20]:
pd.isnull(obj4)

Cal      True
Ohio    False
NY       True
dtype: bool

In [21]:
pd.isnull(obj4).sum()

2

In [22]:
pd.notnull(obj4).sum()

1

In [23]:
obj4.isnull()

Cal      True
Ohio    False
NY       True
dtype: bool

In [24]:
obj.isnull().sum()

0

In [25]:
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [26]:
obj4

Cal       NaN
Ohio    344.0
NY        NaN
dtype: float64

In [27]:
obj3 + obj4

Cal        NaN
NY         NaN
Ohio     688.0
Texas      NaN
Utah       NaN
dtype: float64

In [28]:
obj4.name = 'population'

In [29]:
obj4.index.name = 'state'

In [30]:
obj4

state
Cal       NaN
Ohio    344.0
NY        NaN
Name: population, dtype: float64

In [31]:
obj

0    4
1    8
2   -5
3    2
dtype: int64

In [32]:
obj.index = ['b', 's', 'j', 'r']
obj

b    4
s    8
j   -5
r    2
dtype: int64

## DataFrame

In [33]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(
    data, 
    columns=['year', 'state', 'pop', 'debt'], 
    index=['one', 'two', 'three', 'four', 'five', 'six']
)
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [40]:
type(frame2['state'])

pandas.core.series.Series

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [42]:
frame2['state']['two':'four']

two        Ohio
three      Ohio
four     Nevada
Name: state, dtype: object

In [43]:
frame2['state'].name

'state'

In [44]:
frame2['state'].index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [45]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [46]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [47]:
frame2['debt'] = np.arange(6.0)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [48]:
val = pd.Series(
    [-1.2, -1.5, -1.7], 
    index=['two', 'four', 'seven']
    )
val

two     -1.2
four    -1.5
seven   -1.7
dtype: float64

In [49]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [50]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [51]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
pop = {
    'Nevada' : {2001: 2.4, 2002: 2.9}, 
    'Ohio'   : {2000: 1.5, 2001: 1.7, 2002: 3.6}
}

In [54]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [55]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [56]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [57]:
pdata = {
    'Ohio'   : frame3['Ohio'][:-1],
    'Nevada' : frame3['Nevada'][:2]
}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [58]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [59]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [60]:
three_d_arr = np.array([
    [[1, 2], [2, 1]], 
    [[3, 4], [4, 3]],
    [[5, 6], [6, 5]]
])
three_d_arr

array([[[1, 2],
        [2, 1]],

       [[3, 4],
        [4, 3]],

       [[5, 6],
        [6, 5]]])

In [61]:
three_d_arr[0]

array([[1, 2],
       [2, 1]])

In [62]:
frame3['3d_array'] = [three_d_arr[0], three_d_arr[1], three_d_arr[2]]
frame3

state  Nevada  Ohio          3d_array
year                                 
2001      2.4   1.7  [[1, 2], [2, 1]]
2002      2.9   3.6  [[3, 4], [4, 3]]
2000      NaN   1.5  [[5, 6], [6, 5]]

In [63]:
frame3.values

array([[2.4, 1.7, array([[1, 2],
       [2, 1]])],
       [2.9, 3.6, array([[3, 4],
       [4, 3]])],
       [nan, 1.5, array([[5, 6],
       [6, 5]])]], dtype=object)

In [64]:
frame3['3d_array']

year
2001    [[1, 2], [2, 1]]
2002    [[3, 4], [4, 3]]
2000    [[5, 6], [6, 5]]
Name: 3d_array, dtype: object

In [65]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## index objects

In [66]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [67]:
index[1:]

Index(['b', 'c'], dtype='object')

In [68]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [69]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [70]:
obj2.index is labels

True

In [71]:
frame3

state  Nevada  Ohio          3d_array
year                                 
2001      2.4   1.7  [[1, 2], [2, 1]]
2002      2.9   3.6  [[3, 4], [4, 3]]
2000      NaN   1.5  [[5, 6], [6, 5]]

In [72]:
frame3.columns

Index(['Nevada', 'Ohio', '3d_array'], dtype='object', name='state')

In [73]:
'Ohin' in frame3.columns

False

In [74]:
2003 in frame3.index

False

In [75]:
frame3.drop(['3d_array'], axis=1)

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [76]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 essential functionality

### reindexing

In [77]:
obj = pd.Series(
    [4.5, 7.2, -5.3, 3.6], 
    index=['d', 'b','a', 'c']
)
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [78]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [79]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [80]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [81]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [82]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [83]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### drop entires from an axis

In [84]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [85]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [86]:
obj.drop(['d', 'a'])

b    1.0
c    2.0
e    4.0
dtype: float64

In [87]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [88]:

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data.drop(['Ohio', 'Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [92]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [94]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
obj.drop('c', inplace=True)

In [96]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [97]:
data.drop(['one', 'four'], axis=1, inplace=True)

In [98]:
data

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

### indexing, selection, filtering

In [99]:
obj_sr = pd.Series(
    np.arange(4.), 
    index=['a', 'b', 'c', 'd'])
obj_sr

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [100]:
obj_sr['b']

1.0

In [101]:
obj_sr[1]

1.0

In [102]:
obj_sr[2:4]

c    2.0
d    3.0
dtype: float64

In [103]:
obj_sr[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [104]:
obj_sr[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [105]:
obj[[1, 3]]

b    1.0
e    4.0
dtype: float64

In [106]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [107]:
obj['b' : 'c']

b    1.0
dtype: float64

In [108]:
obj[['b', 'c']]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [109]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
d    3.0
e    4.0
dtype: float64

In [110]:
data = pd.DataFrame(
    np.arange(16).reshape((4,4)), 
    index=['Ohio', 'Colo', 'Utah', 'NY'],
    columns=['one', 'two', 'three', 'four']
)
data

one  two  three  four
Ohio    0    1      2     3
Colo    4    5      6     7
Utah    8    9     10    11
NY     12   13     14    15

In [111]:
data['two']

Ohio     1
Colo     5
Utah     9
NY      13
Name: two, dtype: int64

In [112]:
data[['three', 'one']]

three  one
Ohio      2    0
Colo      6    4
Utah     10    8
NY       14   12

In [113]:
data[:2]

one  two  three  four
Ohio    0    1      2     3
Colo    4    5      6     7

In [114]:
# apply a boolean mask on the df
# only cells marked as 'true' will be selected
data[data['three'] > 5]

one  two  three  four
Colo    4    5      6     7
Utah    8    9     10    11
NY     12   13     14    15

In [115]:
# create a boolean mask
data < 5

one    two  three   four
Ohio   True   True   True   True
Colo   True  False  False  False
Utah  False  False  False  False
NY    False  False  False  False

In [116]:
# apply the booleam mask to the df
# value will be assigned only to cells masked as 'true'
data[data < 5] = 999
data

one  two  three  four
Ohio  999  999    999   999
Colo  999    5      6     7
Utah    8    9     10    11
NY     12   13     14    15

## selection with loc and iloc

In [117]:
data = pd.DataFrame(
    np.arange(16).reshape((4,4)), 
    index=['Ohio', 'Colo', 'Utah', 'NY'],
    columns=['one', 'two', 'three', 'four']
)
data

one  two  three  four
Ohio    0    1      2     3
Colo    4    5      6     7
Utah    8    9     10    11
NY     12   13     14    15

In [118]:
data.loc['Colo', ['two', 'four']]

two     5
four    7
Name: Colo, dtype: int64

In [119]:
data.loc['Colo', 'two':'four']

two      5
three    6
four     7
Name: Colo, dtype: int64

In [120]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [121]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [122]:
data.iloc[:, :3][data['three'] > 5]

one  two  three
Colo    4    5      6
Utah    8    9     10
NY     12   13     14

In [123]:
data.at['NY' , 'three']

14

In [124]:
data.iat[0 , 2]

2

## integer indexes

In [125]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [126]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [127]:
ser2[-1]

2.0

In [128]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [129]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [130]:
ser.iloc[:1]

0    0.0
dtype: float64

## arithmetic and data alignment

In [134]:
s1 = pd.Series(
    [7.3, -2.5, 3.4, 1.5],
    index=['a', 'c', 'd', 'e'])

s2 = pd.Series(
    [-2.1, 3.6, -1.5, 4, 3.1],
    index=['a', 'c', 'e', 'f', 'g'])

In [135]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [133]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [136]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [137]:
df1 = pd.DataFrame(
    np.arange(9.).reshape((3, 3)), 
    columns=list('bcd'),
    index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(
    np.arange(12.).reshape((4, 3)), 
    columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [138]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [139]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [140]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [141]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [142]:
df1

A
0  1
1  2

In [143]:
df2

B
0  3
1  4

In [144]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

## arithmetic methods with fill values

In [145]:
df1 = pd.DataFrame(
    np.arange(12.).reshape((3, 4)),
    columns=list('abcd'))

df2 = pd.DataFrame(
    np.arange(20.).reshape((4, 5)),
    columns=list('abcde'))

In [146]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [147]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [148]:
df2.loc[1, 'b'] = np.nan

In [149]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [150]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [151]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [152]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [155]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [156]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [157]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [158]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## operations btw dataframe and series

In [159]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [160]:
arr[0]

array([0., 1., 2., 3.])

In [161]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [162]:
frame = pd.DataFrame(
    np.arange(12.).reshape((4, 3)),
    columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [163]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [164]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [165]:
series.name

'Utah'

In [166]:
series.index

Index(['b', 'd', 'e'], dtype='object')

In [167]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [169]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [170]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [172]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [173]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## function application and mapping

In [174]:
frame = pd.DataFrame(
    np.random.randn(4, 3), columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [175]:
np.abs(frame)

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [178]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [179]:
frame.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [180]:
frame.apply(f, axis=1)


Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

### the function passed to **_apply()_** can return a Seriers with multiple values

In [181]:
def f(x):
    return pd.Series(
        [x.min(), x.max()],
        index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [184]:
f_format = lambda x: '%.2f' % x
frame.applymap(f_format)

b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [185]:
frame['e'].map(f_format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

## sorting and ranking

In [186]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [187]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [193]:
frame = pd.DataFrame(
    np.arange(8).reshape((2, 4)),
    index=list('ZA'),
    columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
Z  0  1  2  3
A  4  5  6  7

In [194]:
frame.sort_index()

d  a  b  c
A  4  5  6  7
Z  0  1  2  3

In [195]:
frame.sort_index(axis=1)

a  b  c  d
Z  1  2  3  0
A  5  6  7  4

In [196]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
Z  0  3  2  1
A  4  7  6  5

In [197]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [198]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [199]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [200]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [201]:
frame = pd.DataFrame({
    'b': [4, 7, -3, 2], 
    'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [202]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [203]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [204]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [205]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [206]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [207]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [208]:
frame = pd.DataFrame({
    'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
    'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [209]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## axis indexes with duplicate labels